version: '2'

services:
  shared-build:
    build: pkg/
    image: shared-image:latest
  auth:
    build: cmd/auth/
    ports:
      - "3687:3687"
    command: /auth/main
    networks:
      - all
  server:
    build: cmd/http/
    ports:
      - "8080:8080"
    command: /http/main
    networks:
      - all
  tarantool:
    build: db/
    image: tarantool/tarantool:2.2.1
    ports:
      - "3301:3301"
    networks:
      - all
networks:
  all:
