version: '2'

services:
  shared-build:
    build: .
    image: shared-image:latest

  auth:
    build: cmd/auth/
    ports:
      - 3687:3687
    networks:
      - all
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
    networks:
      - all

  mock:
    build: cmd/mock
    ports:
      - 25:25
    networks:
      - all

  notifications:
    build: cmd/notifications
    networks:
      - all
    depends_on:
      - rabbitmq

  server:
    build: cmd/http/
    ports:
      - 8080:8080
    networks:
      - all
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "guest"
      MYSQL_DATABASE: shop
    ports:
      - 3307:3306
    volumes:
      - './pkg/database/:/docker-entrypoint-initdb.d/'
    networks:
      - all
networks:
  all:
