version: '2'

services:
  shared-build:
    build: .
    image: shared-image:latest
  auth:
    build: auth
    image: auth:latest
    ports:
      - "3687:3687"
    command: /auth/main
    depends_on:
      - tarantool
    networks:
      - all
  server:
    build: http
    image: server:latest
    ports:
      - "8080:8080"
    command: /http/main
    depends_on:
      - tarantool
    networks:
      - all
  tarantool:
    build: db
    image: tarantool/tarantool:2.2.1
    ports:
      - "3301:3301"
    networks:
      - all
networks:
  all:
