version: '2'

services:
  shared-build:
    build: .
    image: shared-image:latest

  auth:
    build: cmd/auth/
    ports:
      - 3687:3687
      - 3867:3867
    networks:
      - auth
      - notifications
      - verification
      - uploader
    depends_on:
      - rabbitmq

  uploader:
    build: cmd/uploader/
    networks:
      - uploader
      - load
    depends_on:
      - rabbitmqupload
    volumes:
      - "./pkg/tmp/:/files"

  importer:
    build: cmd/importer/
    ports:
      - 3838:3838
    networks:
      - uploader
      - load
    volumes:
    - "./pkg/tmp/:/files"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
    networks:
      - notifications

  rabbitmqupload:
    image: rabbitmq:3-management
    ports:
      - 5762:5672
    networks:
      - uploader

  mock:
    build: cmd/mock
    ports:
      - 25:25
    networks:
      - notifications

  notifications:
    build: cmd/notifications
    networks:
      - notifications
    depends_on:
      - rabbitmq

  server:
    build: cmd/http/
    ports:
      - 8080:8080
    networks:
      - server
      - verification
      - load
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "guest"
      MYSQL_DATABASE: shop
    ports:
      - 3307:3306
    volumes:
      - './pkg/database/:/docker-entrypoint-initdb.d/'
    networks:
      - auth
      - server
      - uploader
networks:
  auth:
  notifications:
  server:
  uploader:
  verification:
  load:
